const { buildProduccion, runProduccion } = require('./produccion');

module.exports = {
  buildProduccion,
  runProduccion,
  insertProgramada: require('./insertProgramada.js'),
  getProgramada: require('./getProgramada.js'),
  updateProgramada: require('./updateProgramada.js'),
  getProgramadaTotal: require('./getProgramadaTotal.js'),
  getProgColor: require('./getProgColor.js'),
  getMachines: require('./getMachines.js'),
  insertColorCodes: require('./insertColorCodes.js'),
  insertDistr: require('./insertDistr.js'),
  getArticulo: require('./getArticulo.js'),
  getArticuloColorDistr: require('./getArticuloColorDistr.js'),
  getArticuloColorCodes: require('./getArticuloColorCodes.js'),
  insertArticulo: require('./insertArticulo.js'),
  getProgColorTable: require('./getProgColorTable.js'),
  updateProgColorDoc: require('./updateProgColorDoc.js'),
  getProgActualDate: require('./getProgActualDate.js'),
  getProgLoadDates: require('./getProgLoadDates.js'),
  insertColor: require('./insertColor.js'),
  insertProgStartDate: require('./insertProgStartDate.js'),
  getCurrArtColorDistr: require('./getCurrArtColorDistr.js'),
  updateArticuloTipo: require('./updateArticulo.js'),
  getProductionsMonitor: require('./getProductionsMonitor.js'),
  getDailyProduction: require('./getDailyProduction.js'),
  getCurrWEff: require('./getCurrWEff.js'),
  getDailyWEff: require('./getDailyWEff.js'),
  getMonthSaldo: require('./getMonthSaldo.js'),
  getCambios: require('./getCambios.js'),
  getOfflineMachines: require('./getOfflineMachines.js'),
  getGruposMachines: require('./getGruposMachines.js'),
  getGruposTargets: require('./getGruposTargets.js'),
  getDistribucionColores: require('./getDistribucionColores.js'),
  getMachineProduction: require('./getMachineProduction.js'),
  getMachineDefects: require('./getMachineDefects.js'),
  getDisponiblesMachines: require('./getDisponiblesMachines.js'),
  searchColorCodes: require('./searchColorCodes.js'),
  getAppColores: require('./getAppColores.js'),
  updateStyleCode: require('./updateStyleCode.js'),
  getColorCodesLog: require('./getColorCodesLog.js'),
  updateColor: require('./updateColor.js'),
  getProgramadaHistory: require('./getProgramadaHistory.js'),
};


